import React, { useEffect, useMemo, useState } from "react";
import api, { formatApiError } from "../lib/api";
import { Building2, CheckCircle2, FlaskConical, KeyRound, Network, Plus, RefreshCw, ShieldCheck, Trash2, Users, Workflow, SlidersHorizontal } from "lucide-react";
import { toast } from "sonner";

const inputClass = "w-full px-4 py-2.5 rounded-lg bg-[#0a0d14]/80 border border-white/10 text-sm";
const buttonClass = "w-full py-3 rounded-lg bg-yellow-500 text-black font-bold hover:bg-yellow-400 flex items-center justify-center gap-2";
const blank = { organizations: [], roles: [], permissions: [], assignments: [], users: [], groups: [], memberships: [], delegations: [], policies: [] };
const cleanError = (error, fallback) => formatApiError(error?.response?.data?.detail) || fallback;

export default function AccessControlPage() {
  const [data, setData] = useState(blank);
  const [tab, setTab] = useState("overview");
  const [loading, setLoading] = useState(true);
  const [organization, setOrganization] = useState({ name: "", code: "", kind: "department", parent_id: "" });
  const [role, setRole] = useState({ name: "", code: "", description: "", permissions: [], clearance: "internal", active: true });
  const [assignment, setAssignment] = useState({ user_id: "", role_id: "", scope_type: "global", scope_id: "", expires_at: "" });
  const [group, setGroup] = useState({ name: "", code: "", description: "", unit_id: "" });
  const [membership, setMembership] = useState({ user_id: "", group_id: "" });
  const [delegation, setDelegation] = useState({ delegator_id: "", delegate_id: "", permissions: [], scope_id: "", starts_at: "", expires_at: "" });
  const [policy, setPolicy] = useState({ name: "", action: "*", effect: "deny", priority: 100, require_mfa: false, max_amount: "" });
  const [simulation, setSimulation] = useState({ user_id: "", action: "project.view", resource: { classification: "internal" }, context: { mfa_verified: true, amount: 0 } });
  const [decision, setDecision] = useState(null);

  const load = async () => {
    setLoading(true);
    try { setData({ ...blank, ...(await api.get("/access/bootstrap")).data }); }
    catch (error) { toast.error(cleanError(error, "تعذر تحميل نسيج الصلاحيات")); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);

  const users = useMemo(() => Object.fromEntries(data.users.map((item) => [item.id, item])), [data.users]);
  const roles = useMemo(() => Object.fromEntries(data.roles.map((item) => [item.id, item])), [data.roles]);
  const orgs = useMemo(() => Object.fromEntries(data.organizations.map((item) => [item.id, item])), [data.organizations]);
  const groups = useMemo(() => Object.fromEntries(data.groups.map((item) => [item.id, item])), [data.groups]);
  const toggle = (items, value) => items.includes(value) ? items.filter((item) => item !== value) : [...items, value];

  const mutate = async (request, success, fallback, after) => {
    try { await request(); toast.success(success); if (after) after(); await load(); }
    catch (error) { toast.error(cleanError(error, fallback)); }
  };

  if (loading) return <div className="p-8 text-slate-400">جارٍ تحميل نسيج الصلاحيات المؤسسية...</div>;

  const tabs = [
    ["overview", ShieldCheck, "الملخص"], ["structure", Building2, "الهيكل"],
    ["roles", KeyRound, "الأدوار"], ["assignments", Network, "التعيينات"],
    ["groups", Users, "المجموعات"], ["delegations", Workflow, "التفويضات"],
    ["policies", SlidersHorizontal, "السياسات"], ["simulator", FlaskConical, "المحاكي"],
  ];

  return (
    <div className="space-y-6" dir="rtl" data-testid="access-control-page">
      <div className="flex items-end justify-between gap-4 flex-wrap">
        <div><div className="text-xs tracking-[0.18em] text-yellow-500/80">ARAAK ACCESS FABRIC</div><h1 className="font-heading text-4xl font-black mt-2 flex items-center gap-3"><ShieldCheck className="text-yellow-500"/> نسيج الهوية والصلاحيات</h1><p className="text-slate-500 text-sm mt-2">أدوار مرنة، نطاقات تنظيمية، مجموعات، تفويضات مؤقتة، تصنيفات وسياسات قابلة للتفسير.</p></div>
        <button onClick={load} className="px-4 py-2 rounded-lg border border-white/10 hover:bg-white/5 flex items-center gap-2"><RefreshCw size={16}/> تحديث</button>
      </div>

      <div className="flex gap-2 flex-wrap border-b border-white/5 pb-3">{tabs.map(([id, Icon, label]) => <button key={id} onClick={() => setTab(id)} className={`px-4 py-2 rounded-lg text-sm flex items-center gap-2 ${tab === id ? "bg-yellow-500/10 border border-yellow-500/20 text-yellow-300" : "text-slate-400 hover:bg-white/5"}`}><Icon size={15}/>{label}</button>)}</div>

      {tab === "overview" && <div className="grid md:grid-cols-4 gap-4">
        {[["الوحدات", data.organizations.length, Building2], ["قوالب الأدوار", data.roles.length, KeyRound], ["التعيينات النشطة", data.assignments.filter((item) => item.active !== false).length, Network], ["المستخدمون", data.users.length, Users]].map(([label, value, Icon]) => <div key={label} className="glass-card p-5"><Icon className="text-yellow-500 mb-4"/><div className="text-3xl font-black">{value}</div><div className="text-xs text-slate-500 mt-1">{label}</div></div>)}
        <div className="md:col-span-4 glass-card p-6"><h2 className="font-bold text-xl mb-4">سلسلة قرار الوصول</h2><div className="grid md:grid-cols-5 gap-3">{["الهوية", "الدور", "النطاق", "العلاقة", "السياق والسياسة"].map((item, index) => <div key={item} className="rounded-lg border border-white/10 p-4"><div className="text-yellow-400 text-xs mb-2">0{index + 1}</div>{item}</div>)}</div></div>
      </div>}

      {tab === "structure" && <div className="grid lg:grid-cols-[1fr_380px] gap-5">
        <div className="glass-card p-5 space-y-2">{data.organizations.map((item) => <div key={item.id} className="flex justify-between gap-4 rounded-lg border border-white/5 p-3"><div><div className="font-medium">{item.name}</div><div className="text-xs text-slate-500">{item.kind} · {item.code}</div></div><div className="text-xs text-slate-600">{item.parent_id ? orgs[item.parent_id]?.name : "الجذر"}</div></div>)}</div>
        <form onSubmit={(event) => { event.preventDefault(); mutate(() => api.post("/access/organizations", { ...organization, parent_id: organization.parent_id || null }), "تم إنشاء الوحدة التنظيمية", "تعذر إنشاء الوحدة", () => setOrganization({ name: "", code: "", kind: "department", parent_id: "" })); }} className="glass-card p-5 space-y-3 h-fit"><h2 className="font-bold text-lg">إضافة وحدة تنظيمية</h2><input required className={inputClass} placeholder="اسم الوحدة" value={organization.name} onChange={(event) => setOrganization({...organization, name: event.target.value})}/><input required className={inputClass} placeholder="رمز فريد" value={organization.code} onChange={(event) => setOrganization({...organization, code: event.target.value.toUpperCase()})}/><select className={inputClass} value={organization.kind} onChange={(event) => setOrganization({...organization, kind: event.target.value})}>{["company", "department", "branch", "committee", "project", "team"].map((item) => <option key={item}>{item}</option>)}</select><select className={inputClass} value={organization.parent_id} onChange={(event) => setOrganization({...organization, parent_id: event.target.value})}><option value="">بلا وحدة أم</option>{data.organizations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className={buttonClass}><Plus size={16}/> إنشاء الوحدة</button></form>
      </div>}

      {tab === "roles" && <div className="grid lg:grid-cols-[1fr_430px] gap-5">
        <div className="space-y-3">{data.roles.map((item) => <div key={item.id} className="glass-card p-5"><div className="flex justify-between gap-4"><div><div className="font-bold text-lg">{item.name}</div><div className="text-xs text-slate-500">{item.code}{item.system ? " · نظامي" : ""}</div></div><span className="text-xs">{item.permissions?.length || 0} صلاحية</span></div><p className="text-sm text-slate-400 mt-3">{item.description}</p><div className="flex gap-1 flex-wrap mt-3">{item.permissions?.slice(0, 12).map((permission) => <span key={permission} className="text-[10px] px-2 py-1 rounded bg-yellow-500/5 text-yellow-300">{permission}</span>)}</div></div>)}</div>
        <form onSubmit={(event) => { event.preventDefault(); mutate(() => api.post("/access/roles", role), "تم إنشاء قالب الدور", "تعذر إنشاء الدور", () => setRole({ name: "", code: "", description: "", permissions: [], clearance: "internal", active: true })); }} className="glass-card p-5 space-y-3 h-fit"><h2 className="font-bold text-lg">إنشاء قالب دور</h2><input required className={inputClass} placeholder="اسم الدور" value={role.name} onChange={(event) => setRole({...role, name: event.target.value})}/><input required className={inputClass} placeholder="role_code" value={role.code} onChange={(event) => setRole({...role, code: event.target.value.toLowerCase().replace(/\s+/g, "_")})}/><textarea className={inputClass} placeholder="وصف الدور" value={role.description} onChange={(event) => setRole({...role, description: event.target.value})}/><select className={inputClass} value={role.clearance} onChange={(event) => setRole({...role, clearance: event.target.value})}>{["internal", "restricted", "confidential", "executive_secret", "financial_sensitive", "legal_privileged"].map((item) => <option key={item}>{item}</option>)}</select><div className="max-h-72 overflow-y-auto rounded-lg border border-white/5 p-3 space-y-2">{data.permissions.map((permission) => <label key={permission.code} className="flex gap-2 text-xs"><input type="checkbox" checked={role.permissions.includes(permission.code)} onChange={() => setRole({...role, permissions: toggle(role.permissions, permission.code)})}/>{permission.code}</label>)}</div><button className={buttonClass}><Plus size={16}/> إنشاء الدور</button></form>
      </div>}

      {tab === "assignments" && <div className="space-y-5">
        <form onSubmit={(event) => { event.preventDefault(); mutate(() => api.post("/access/assignments", { ...assignment, group_id: null, scope_id: assignment.scope_id || null, starts_at: null, expires_at: assignment.expires_at || null }), "تم إسناد الدور", "تعذر إسناد الدور"); }} className="glass-card p-5 grid md:grid-cols-3 gap-3"><select required className={inputClass} value={assignment.user_id} onChange={(event) => setAssignment({...assignment, user_id: event.target.value})}><option value="">اختر المستخدم</option>{data.users.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.email}</option>)}</select><select required className={inputClass} value={assignment.role_id} onChange={(event) => setAssignment({...assignment, role_id: event.target.value})}><option value="">اختر الدور</option>{data.roles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={inputClass} value={assignment.scope_type} onChange={(event) => setAssignment({...assignment, scope_type: event.target.value})}>{["global", "organization", "unit", "project", "resource"].map((item) => <option key={item}>{item}</option>)}</select><select className={inputClass} value={assignment.scope_id} onChange={(event) => setAssignment({...assignment, scope_id: event.target.value})}><option value="">كل النطاقات</option>{data.organizations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input className={inputClass} type="datetime-local" value={assignment.expires_at} onChange={(event) => setAssignment({...assignment, expires_at: event.target.value})}/><button className={buttonClass}><Plus size={16}/> إسناد الدور</button></form>
        <div className="glass-card p-2 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-right text-xs text-slate-500"><th className="p-3">المستخدم</th><th>الدور</th><th>النطاق</th><th>الانتهاء</th><th></th></tr></thead><tbody>{data.assignments.filter((item) => item.active !== false).map((item) => <tr key={item.id} className="border-t border-white/5"><td className="p-3">{users[item.user_id]?.name || groups[item.group_id]?.name || "مجموعة"}</td><td>{roles[item.role_id]?.name}</td><td>{item.scope_type} · {orgs[item.scope_id]?.name || "عام"}</td><td>{item.expires_at ? new Date(item.expires_at).toLocaleString("ar-SA") : "مفتوح"}</td><td><button onClick={() => mutate(() => api.delete(`/access/assignments/${item.id}`), "تم إلغاء التعيين", "تعذر إلغاء التعيين")} className="p-2 text-rose-300"><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>
      </div>}

      {tab === "groups" && <div className="grid lg:grid-cols-2 gap-5">
        <div className="space-y-5"><form onSubmit={(event) => { event.preventDefault(); mutate(() => api.post("/access/groups", { ...group, unit_id: group.unit_id || null }), "تم إنشاء المجموعة", "تعذر إنشاء المجموعة", () => setGroup({ name: "", code: "", description: "", unit_id: "" })); }} className="glass-card p-5 space-y-3"><h2 className="font-bold text-lg">إنشاء مجموعة عمل</h2><input required className={inputClass} placeholder="اسم المجموعة" value={group.name} onChange={(event) => setGroup({...group, name: event.target.value})}/><input required className={inputClass} placeholder="GROUP_CODE" value={group.code} onChange={(event) => setGroup({...group, code: event.target.value.toUpperCase()})}/><textarea className={inputClass} placeholder="وصف المجموعة" value={group.description} onChange={(event) => setGroup({...group, description: event.target.value})}/><select className={inputClass} value={group.unit_id} onChange={(event) => setGroup({...group, unit_id: event.target.value})}><option value="">بلا وحدة مرتبطة</option>{data.organizations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className={buttonClass}><Plus size={16}/> إنشاء المجموعة</button></form><div className="glass-card p-5 space-y-2">{data.groups.map((item) => <div key={item.id} className="rounded-lg border border-white/5 p-3"><div className="font-bold">{item.name}</div><div className="text-xs text-slate-500">{item.code} · {orgs[item.unit_id]?.name || "غير مرتبطة"}</div></div>)}</div></div>
        <div className="space-y-5"><form onSubmit={(event) => { event.preventDefault(); mutate(() => api.post("/access/memberships", membership), "تمت إضافة العضوية", "تعذر إضافة العضوية"); }} className="glass-card p-5 space-y-3"><h2 className="font-bold text-lg">إضافة عضو</h2><select required className={inputClass} value={membership.user_id} onChange={(event) => setMembership({...membership, user_id: event.target.value})}><option value="">اختر المستخدم</option>{data.users.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required className={inputClass} value={membership.group_id} onChange={(event) => setMembership({...membership, group_id: event.target.value})}><option value="">اختر المجموعة</option>{data.groups.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className={buttonClass}><Plus size={16}/> إضافة العضوية</button></form><div className="glass-card p-5 space-y-2">{data.memberships.map((item) => <div key={item.id} className="flex justify-between gap-3 rounded-lg border border-white/5 p-3"><span>{users[item.user_id]?.name} ← {groups[item.group_id]?.name}</span><button onClick={() => mutate(() => api.delete(`/access/memberships/${item.id}`), "تمت إزالة العضوية", "تعذر إزالة العضوية")} className="text-rose-300"><Trash2 size={14}/></button></div>)}</div></div>
      </div>}

      {tab === "delegations" && <div className="space-y-5">
        <form onSubmit={(event) => { event.preventDefault(); mutate(() => api.post("/access/delegations", { ...delegation, scope_id: delegation.scope_id || null, exclusions: [] }), "تم إنشاء التفويض", "تعذر إنشاء التفويض"); }} className="glass-card p-5 grid md:grid-cols-2 gap-3"><select required className={inputClass} value={delegation.delegator_id} onChange={(event) => setDelegation({...delegation, delegator_id: event.target.value})}><option value="">صاحب الصلاحية</option>{data.users.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required className={inputClass} value={delegation.delegate_id} onChange={(event) => setDelegation({...delegation, delegate_id: event.target.value})}><option value="">المفوّض إليه</option>{data.users.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={inputClass} value={delegation.scope_id} onChange={(event) => setDelegation({...delegation, scope_id: event.target.value})}><option value="">نطاق عام</option>{data.organizations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input required className={inputClass} type="datetime-local" value={delegation.starts_at} onChange={(event) => setDelegation({...delegation, starts_at: event.target.value})}/><input required className={inputClass} type="datetime-local" value={delegation.expires_at} onChange={(event) => setDelegation({...delegation, expires_at: event.target.value})}/><div className="md:col-span-2 max-h-52 overflow-y-auto rounded-lg border border-white/5 p-3 grid md:grid-cols-2 gap-2">{data.permissions.map((permission) => <label key={permission.code} className="flex gap-2 text-xs"><input type="checkbox" checked={delegation.permissions.includes(permission.code)} onChange={() => setDelegation({...delegation, permissions: toggle(delegation.permissions, permission.code)})}/>{permission.code}</label>)}</div><button className={`${buttonClass} md:col-span-2`}><Workflow size={16}/> إنشاء التفويض</button></form>
        <div className="glass-card p-2 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-right text-xs text-slate-500"><th className="p-3">من</th><th>إلى</th><th>الصلاحيات</th><th>الانتهاء</th><th></th></tr></thead><tbody>{data.delegations.map((item) => <tr key={item.id} className="border-t border-white/5"><td className="p-3">{users[item.delegator_id]?.name}</td><td>{users[item.delegate_id]?.name}</td><td>{item.permissions?.length || 0}</td><td>{new Date(item.expires_at).toLocaleString("ar-SA")}</td><td><button onClick={() => mutate(() => api.delete(`/access/delegations/${item.id}`), "تم إلغاء التفويض", "تعذر إلغاء التفويض")} className="p-2 text-rose-300"><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>
      </div>}

      {tab === "policies" && <div className="grid lg:grid-cols-[1fr_400px] gap-5">
        <div className="space-y-3">{data.policies.map((item) => <div key={item.id} className="glass-card p-5"><div className="flex justify-between"><div><div className="font-bold">{item.name}</div><div className="text-xs text-slate-500">{item.action} · أولوية {item.priority}</div></div><span className={`text-xs px-2 py-1 rounded ${item.effect === "allow" ? "bg-emerald-500/10 text-emerald-300" : "bg-rose-500/10 text-rose-300"}`}>{item.effect}</span></div><pre className="text-[10px] text-slate-500 mt-3 whitespace-pre-wrap">{JSON.stringify(item.conditions || {}, null, 2)}</pre></div>)}</div>
        <form onSubmit={(event) => { event.preventDefault(); const conditions = {}; if (policy.require_mfa) conditions.require_mfa = true; if (policy.max_amount !== "") conditions.max_amount = Number(policy.max_amount); mutate(() => api.post("/access/policies", { name: policy.name, action: policy.action, effect: policy.effect, priority: Number(policy.priority), conditions, active: true }), "تم إنشاء السياسة", "تعذر إنشاء السياسة", () => setPolicy({ name: "", action: "*", effect: "deny", priority: 100, require_mfa: false, max_amount: "" })); }} className="glass-card p-5 space-y-3 h-fit"><h2 className="font-bold text-lg">إنشاء سياسة سياقية</h2><input required className={inputClass} placeholder="اسم السياسة" value={policy.name} onChange={(event) => setPolicy({...policy, name: event.target.value})}/><select className={inputClass} value={policy.action} onChange={(event) => setPolicy({...policy, action: event.target.value})}><option value="*">كل الإجراءات</option>{data.permissions.map((item) => <option key={item.code}>{item.code}</option>)}</select><select className={inputClass} value={policy.effect} onChange={(event) => setPolicy({...policy, effect: event.target.value})}><option value="deny">منع</option><option value="allow">سماح</option></select><input className={inputClass} type="number" value={policy.priority} onChange={(event) => setPolicy({...policy, priority: event.target.value})} placeholder="الأولوية"/><input className={inputClass} type="number" value={policy.max_amount} onChange={(event) => setPolicy({...policy, max_amount: event.target.value})} placeholder="الحد المالي الأقصى"/><label className="flex gap-2 text-sm"><input type="checkbox" checked={policy.require_mfa} onChange={(event) => setPolicy({...policy, require_mfa: event.target.checked})}/> يشترط المصادقة الثنائية</label><button className={buttonClass}><Plus size={16}/> إنشاء السياسة</button></form>
      </div>}

      {tab === "simulator" && <div className="grid lg:grid-cols-2 gap-5">
        <form onSubmit={async (event) => { event.preventDefault(); try { setDecision((await api.post("/access/simulate", simulation)).data); } catch (error) { toast.error(cleanError(error, "تعذر تشغيل المحاكاة")); } }} className="glass-card p-6 space-y-4"><h2 className="font-bold text-xl">محاكاة قرار الوصول</h2><select required className={inputClass} value={simulation.user_id} onChange={(event) => setSimulation({...simulation, user_id: event.target.value})}><option value="">اختر المستخدم</option>{data.users.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.email}</option>)}</select><select className={inputClass} value={simulation.action} onChange={(event) => setSimulation({...simulation, action: event.target.value})}>{data.permissions.map((item) => <option key={item.code}>{item.code}</option>)}</select><select className={inputClass} value={simulation.resource.classification} onChange={(event) => setSimulation({...simulation, resource: {...simulation.resource, classification: event.target.value}})}>{["internal", "restricted", "confidential", "executive_secret", "financial_sensitive", "legal_privileged"].map((item) => <option key={item}>{item}</option>)}</select><input className={inputClass} type="number" value={simulation.context.amount} onChange={(event) => setSimulation({...simulation, context: {...simulation.context, amount: Number(event.target.value)}})} placeholder="قيمة العملية"/><label className="flex gap-2 text-sm"><input type="checkbox" checked={simulation.context.mfa_verified} onChange={(event) => setSimulation({...simulation, context: {...simulation.context, mfa_verified: event.target.checked}})}/> تم التحقق بالمصادقة الثنائية</label><button className={buttonClass}><FlaskConical size={16}/> تقييم القرار</button></form>
        <div className="glass-card p-6">{decision ? <><div className={`flex items-center gap-3 text-3xl font-black ${decision.allowed ? "text-emerald-400" : "text-rose-400"}`}>{decision.allowed && <CheckCircle2/>}{decision.allowed ? "مسموح" : "مرفوض"}</div><div className="mt-5 space-y-2">{decision.reasons.map((reason, index) => <div key={index} className="rounded-lg border border-white/5 p-3 text-sm">{reason}</div>)}</div><div className="text-xs text-slate-500 mt-4">الأدوار المطابقة: {decision.matched_roles.join("، ") || "لا يوجد"}</div></> : <div className="text-slate-500">شغّل المحاكاة لعرض سبب السماح أو المنع بالتفصيل.</div>}</div>
      </div>}
    </div>
  );
}
